In [1]:
import pandas as pd

TARGET_PATH = '../data/data3.csv'

df = pd.read_csv(TARGET_PATH,encoding='cp949')

print(df.columns.to_list())

# df[(df['수출입구분명'].isin(['수입환적','수출환적']))]
# df[(df['수출입구분명'].isin(['수입환적','수출환적']))&df['화물종류'].isin(['컨테이너화물'])&df['부두구분명'].isin(['컨테이너부두'])]#['시설코드'].unique().tolist()

df

# 부두구분명 컨테이너부두 88.8% vs 일반부두 11.2%
# 화물종류 컨테이너화물 96.2% vs 일반화물 3.8%

['항구명', '호출부호', '선박명', '년도', '항차', '신고일자', '허가일자', '계선장소시설코드', '계선장소명', '총톤수', '국제총톤수', '외내항구분', '선박국적', '선박종류', '입항일자', '입항목적', '최초출항지항구코드', '최초출항지항구명', '출항예정일시', '전출항지출항일시', '전출항지항구코드', '전출항지항구명', '상태구분', '정보생성일시']

,항구명,호출부호,선박명,년도,항차,신고일자,허가일자,계선장소시설코드,계선장소명,총톤수,...,입항일자,입항목적,최초출항지항구코드,최초출항지항구명,출항예정일시,전출항지출항일시,전출항지항구코드,전출항지항구명,상태구분,정보생성일시
0,부산,9VFX4,KOTA NAGA,2024,4,2024-05-01 00:04:03,2024-05-02 08:45:21,MBS05,신선대부두 5선석,20902.0,...,2024-05-01 03:00:00,양적하,KRPUS,부산,2024-05-02 05:00:00,2024-04-27 16:00:00,CNNSA,NANSHA PT,수정,2024-05-02 08:45:21
1,군산,3E2020,LUCKY JOY,2024,1,2024-05-01 00:42:26,2024-05-02 07:57:16,MB601,6부두 1선석,40040.0,...,2024-04-28 03:42:00,양하,EGPSD,PORT SAID,2024-05-02 17:00:00,2024-03-31 17:00:00,EGPSD,PORT SAID,수정,2024-05-02 07:57:16
2,인천,V3IA2,JUN HE,2024,2,2024-05-01 01:09:27,2024-05-01 08:52:47,MBG03,북항 대주중공업부두 3선석,1496.0,...,2024-05-01 08:40:00,양하,KRCHF,진해,2024-05-02 17:00:00,2024-04-27 14:00:00,JPTHS,TOYOHASHI,수정,2024-05-01 08:52:47
3,부산,A8UX4,MSC SAVONA,2024,3,2024-05-01 01:13:27,2024-05-02 09:34:17,MSN06,신항 2부두 3선석,153115.0,...,2024-05-01 04:15:00,양적하,KRKAN,광양,2024-05-02 07:00:00,2024-04-29 12:00:00,CNTXG,TIANJIN XINGANG PT,수정,2024-05-02 09:34:17
4,부산,3FER7,MSC SOLA,2024,1,2024-05-01 02:11:34,2024-05-02 09:34:25,MSN02,신항 1부두 2선석,131771.0,...,2024-05-01 07:53:00,적하,CNZOS,ZHOUSHAN,2024-05-01 22:00:00,2024-04-29 15:30:00,CNZOS,ZHOUSHAN,수정,2024-05-02 09:34:25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247051,부산,BL2167,FULL LOAD NO.858,2025,1,2025-07-31 16:49:54,2025-07-31 17:13:16,WAN03,남외항 N-3박지,1220.0,...,2025-07-31 15:00:00,선용품적재,TWKHH,KAOHSIUNG,2025-07-31 16:00:00,2025-07-28 10:00:00,TWKHH,KAOHSIUNG,수정,2025-07-31 17:13:16
247052,부산,111002,두라7,2025,25,2025-07-31 17:00:05,2025-07-31 17:20:50,WAE02,E박지 E2 묘지,6402.0,...,2025-07-29 09:00:00,양하,KRTSN,대산,2025-07-31 08:00:00,2025-07-28 00:35:00,KRTSN,대산,수정,2025-07-31 17:20:50
247053,포항신항,3E4126,JIE TAI 8,2025,1,2025-07-31 17:08:35,2025-07-31 17:14:13,MB76B,7부두 76선석 B,2931.0,...,2025-07-30 17:20:00,양하,CNTSN,TIANJIN,2025-08-10 23:00:00,2025-07-26 23:00:00,CNTSN,TIANJIN,수정,2025-07-31 17:14:13
247054,인천,3FBR7,XIN YU JIN XIANG,2025,59,2025-07-31 22:50:49,2025-07-31 23:46:23,MBP16,남항 신국제여객부두 6선석,12304.0,...,2025-07-31 22:15:00,양적하,CNSHP,QINHUANGDAO PT,2025-08-01 11:00:00,2025-07-30 18:55:00,CNSHP,QINHUANGDAO PT,수정,2025-07-31 23:46:23
247055,인천,9V7909,RC SPRING,2025,1,2025-07-31 23:07:55,2025-07-31 23:46:38,MDU03,영흥도 영흥화력3돌핀,51130.0,...,2025-07-31 22:00:00,양하,RUVYP,VOSTOCHNYY PORT,2025-08-14 18:00:00,2025-07-24 18:00:00,RUVYP,VOSTOCHNYY PORT,수정,2025-07-31 23:46:38

In [29]:
# 시설코드로 잘못 기재되어있는 컬럼이름 변경(시설코드 -> 화물종류), 화물종류도 컨테이너구분으로 변경
df.rename(columns={'화물종류': '컨테이너구분'}, inplace=True)
df.rename(columns={'시설코드': '화물종류'}, inplace=True)

# 화물종류 컬럼 위치 변경
target_col = df.pop('화물종류')
df.insert(10, '화물종류', target_col)

In [34]:
# 데이터 확인
df

,연도,월,분기,청코드,내외항구분,수출입구분명,시설명,부두구분명,아외국구분,컨테이너구분,화물종류,화물톤
0,2024,3,1,신항,외항,수입,신항 W 정박지,일반부두,외국선,컨테이너화물,기계류 및 그부품,133
1,2024,4,2,신항,외항,수입,신항 W 정박지,일반부두,아국선,컨테이너화물,기계류 및 그부품,45
2,2024,3,1,신항,외항,수입,신항 W 정박지,일반부두,외국선,컨테이너화물,비철금속 및 그제품,39
3,2024,4,2,신항,외항,수입,신항 W 정박지,일반부두,아국선,컨테이너화물,방직용섬유 및 그제품,22
4,2024,4,2,신항,외항,수입,신항 W 정박지,일반부두,아국선,컨테이너화물,피혁류 및 그제품,39
...,...,...,...,...,...,...,...,...,...,...,...,...
31211,2024,4,2,신항,외항,수출,신항다목적부두,컨테이너부두,외국선,컨테이너화물,조제식품.음료.주류등,81
31212,2024,6,2,신항,외항,수출환적,신항다목적부두,컨테이너부두,외국선,컨테이너화물,조제식품.음료.주류등,44
31213,2024,10,4,신항,외항,수출환적,신항다목적부두,컨테이너부두,아국선,일반화물,조제식품.음료.주류등,3
31214,2024,3,1,신항,외항,수출,신항다목적부두,컨테이너부두,아국선,일반화물,조제식품.음료.주류등,8
31215,2024,7,3,신항,외항,수출,신항다목적부두,컨테이너부두,아국선,일반화물,조제식품.음료.주류등,25

In [35]:
# 결측치 확인
df['화물톤'].isna().sum()

np.int64(0)

### 환적에 해당하는 각 화물 종류별 물동량 확인


항만별, 부두별, 화물종류별 물동량 흐름 파악

수출입 구조 변화
주요 산업별 화물 처리 추세 분석

선박 운영 계획
부두 적재 관리
국가 물류정책 수립
장기적인 무역 흐름
산업별 물류 특성

In [36]:
# df[(df['수출입구분명'].isin(['수입환적','수출환적']))&df['화물종류'].isin(['컨테이너화물'])&df['부두구분명'].isin(['컨테이너부두'])]#['시설코드'].unique().tolist()

print(df.columns.to_list)

print(df.info())

<bound method IndexOpsMixin.tolist of Index(['연도', '월', '분기', '청코드', '내외항구분', '수출입구분명', '시설명', '부두구분명', '아외국구분',
       '컨테이너구분', '화물종류', '화물톤'],
      dtype='str')>
<class 'pandas.DataFrame'>
RangeIndex: 31216 entries, 0 to 31215
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      31216 non-null  int64
 1   월       31216 non-null  int64
 2   분기      31216 non-null  int64
 3   청코드     31216 non-null  str
 4   내외항구분   31216 non-null  str
 5   수출입구분명  31216 non-null  str
 6   시설명     31216 non-null  str
 7   부두구분명   31216 non-null  str
 8   아외국구분   31216 non-null  str
 9   컨테이너구분  31216 non-null  str
 10  화물종류    31216 non-null  str
 11  화물톤     31216 non-null  int64
dtypes: int64(4), str(8)
memory usage: 2.9 MB
None

In [64]:
# 환적 데이터만 추출
trans_df = df[
    (df['수출입구분명'].isin(['수입환적', '수출환적']))
    # & (df['부두구분명'].isin(['컨테이너부두']))
    # & ~(df['컨테이너구분'].isin(['컨테이너화물']))
]

trans_df.groupby(['청코드','화물종류'])['화물톤'].sum().unstack(level=0)

# 화물종류가 너무 많다... 분류가 필요함...

청코드               감천          북항          신항
화물종류
고 철             53.0    122163.0    961766.0
기 타           4698.0   6505530.0  37469357.0
기계류 및 그부품     1586.0   2346523.0  23611140.0
기타광석 및 생산품       NaN    512906.0   4031251.0
기타동.식물성 생산품      NaN    632675.0   7969739.0
당 류              NaN    224897.0    862611.0
동.식물성 유지류    11999.0    120797.0    701037.0
모 래              NaN      5304.0     44591.0
목재.목탄.코르크 등   8485.0   2714143.0  11989536.0
방직용섬유 및 그제품   2700.0  19149027.0  30002455.0
비 료              NaN    350902.0    392244.0
비철금속 및 그제품     363.0    959807.0   8340215.0
석유 정제품           NaN    132134.0    772188.0
석유가스 및 기타가스      NaN      6579.0     12275.0
시멘트              NaN     71682.0     72259.0
양 곡              NaN     94614.0   1245782.0
어패류.갑각류 등    87699.0    431413.0   3123508.0
원 목              NaN      9803.0    697317.0
원유(역청유). 석유      NaN      1034.0       800.0
유연탄              NaN      1105.0     12012.0
육 류          19138.0    102486.0   1348634.0
전기기기 및 그부품    2330.0   3679876.0  16153911.0
제분공업 생산품         NaN    140999.0    619187.0
조제식품.음료.주류등  32885.0   1320958.0  11303644.0
차량 및 그부품       128.0   1096123.0  15394828.0
철강 및 그제품      1180.0   1673468.0  13498426.0
철광석              NaN      1977.0    340771.0
플라스틱.고무및 제품   1677.0   3696631.0  28149490.0
피혁류 및 그제품        NaN     99978.0   2973578.0
항공기.선박 및 부품    178.0     21558.0    788434.0
화학공업 생산품     14037.0   2225120.0  16274412.0